// Shared nav item definitions for every app in the ecosystem
// Used by Release Manager (admin) and any future consumer

export interface AppNavItem {
  slug: string;
  label: string;
  icon: string;
}

export const APP_NAV_ITEMS: Record<string, AppNavItem[]> = {
  chef: [
    { slug: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "prep", label: "Prep Lists", icon: "ClipboardList" },
    { slug: "recipes", label: "Recipes", icon: "ChefHat" },
    { slug: "ingredients", label: "Ingredients", icon: "Utensils" },
    { slug: "invoices", label: "Invoices", icon: "Receipt" },
    { slug: "menu-engineering", label: "Menu Engineering", icon: "Menu" },
    { slug: "equipment", label: "Equipment", icon: "Wrench" },
    { slug: "team", label: "Team", icon: "Users" },
    { slug: "inventory", label: "Inventory", icon: "Package" },
    { slug: "production", label: "Production", icon: "Factory" },
    { slug: "marketplace", label: "Marketplace", icon: "Store" },
    { slug: "allergens", label: "Allergens", icon: "AlertTriangle" },
    { slug: "roster", label: "Roster", icon: "Users" },
    { slug: "calendar", label: "Calendar", icon: "Calendar" },
    { slug: "kitchen-sections", label: "Sections", icon: "LayoutGrid" },
    { slug: "cheatsheets", label: "Cheatsheets", icon: "BookOpen" },
    { slug: "food-safety", label: "Food Safety", icon: "Shield" },
    { slug: "training", label: "Training", icon: "GraduationCap" },
    { slug: "waste-log", label: "Waste Log", icon: "Trash2" },
  ],
  bevos: [
    { slug: "bev-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "bev-cellar", label: "Cellar", icon: "Wine" },
    { slug: "bev-cocktails", label: "Cocktails", icon: "Wine" },
    { slug: "bev-pours", label: "Pours", icon: "TrendingUp" },
    { slug: "bev-bar-prep", label: "Bar Prep", icon: "ClipboardList" },
    { slug: "bev-stocktake", label: "Stocktake", icon: "Package" },
    { slug: "bev-draught", label: "Draught", icon: "Wine" },
    { slug: "bev-coravin", label: "Coravin", icon: "Wine" },
    { slug: "bev-engineering", label: "Engineering", icon: "TrendingUp" },
    { slug: "bev-invoices", label: "Invoices", icon: "Receipt" },
    { slug: "bev-compliance", label: "Compliance", icon: "Shield" },
    { slug: "bev-team", label: "Team", icon: "Users" },
    { slug: "bev-coffee", label: "Coffee", icon: "Wine" },
    { slug: "bev-training", label: "Training", icon: "GraduationCap" },
    { slug: "bev-marketplace", label: "Marketplace", icon: "Store" },
  ],
  posos: [
    { slug: "pos-main", label: "POS", icon: "ShoppingCart" },
    { slug: "pos-kds", label: "KDS", icon: "MonitorPlay" },
    { slug: "pos-tabs", label: "Tabs", icon: "CreditCard" },
    { slug: "pos-functions", label: "Functions", icon: "CalendarDays" },
    { slug: "pos-compliance", label: "Compliance", icon: "Shield" },
    { slug: "pos-audit", label: "Audit Log", icon: "ScrollText" },
    { slug: "pos-analytics", label: "Analytics", icon: "BarChart3" },
    { slug: "pos-menu", label: "Menu Admin", icon: "UtensilsCrossed" },
    { slug: "pos-staff", label: "Staff Admin", icon: "Users" },
    { slug: "pos-store", label: "Store Settings", icon: "Settings" },
  ],
  reservation: [
    { slug: "res-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "res-diary", label: "Diary", icon: "BookOpen" },
    { slug: "res-floor", label: "Floor Plan", icon: "Grid3X3" },
    { slug: "res-bookings", label: "Bookings", icon: "CalendarCheck" },
    { slug: "res-settings", label: "Settings", icon: "Menu" },
  ],
  labour: [
    { slug: "labour-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "labour-roster", label: "Roster", icon: "CalendarDays" },
    { slug: "labour-timesheets", label: "Timesheets", icon: "Clock" },
    { slug: "labour-payroll", label: "Payroll", icon: "DollarSign" },
    { slug: "labour-people", label: "People", icon: "Users" },
  ],
  supply: [
    { slug: "supply-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "supply-orders", label: "Orders", icon: "ShoppingCart" },
    { slug: "supply-suppliers", label: "Suppliers", icon: "Building2" },
    { slug: "supply-receiving", label: "Receiving", icon: "Package" },
    { slug: "supply-price-watch", label: "Price Watch", icon: "TrendingUp" },
  ],
  growth: [
    { slug: "growth-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "growth-campaigns", label: "Campaigns", icon: "Megaphone" },
    { slug: "growth-calendar", label: "Calendar", icon: "CalendarDays" },
    { slug: "growth-segments", label: "Segments", icon: "Users" },
    { slug: "growth-analytics", label: "Analytics", icon: "Menu" },
  ],
  overhead: [
    { slug: "overhead-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "overhead-costs", label: "Costs", icon: "Receipt" },
    { slug: "overhead-alerts", label: "Alerts", icon: "Bell" },
    { slug: "overhead-recurring", label: "Recurring", icon: "TrendingUp" },
    { slug: "overhead-settings", label: "Settings", icon: "Menu" },
  ],
  money: [
    { slug: "money-reactor", label: "Reactor", icon: "Atom" },
    { slug: "money-pnl", label: "P&L", icon: "BarChart3" },
    { slug: "money-trends", label: "Trends", icon: "TrendingUp" },
    { slug: "money-simulator", label: "Scenarios", icon: "FlaskConical" },
    { slug: "money-solutions", label: "Solutions", icon: "Lightbulb" },
    { slug: "money-audit", label: "Quiet Audit", icon: "ShieldCheck" },
    { slug: "money-forensic", label: "Forensic", icon: "FileSearch" },
    { slug: "money-portfolio", label: "Portfolio", icon: "Layers" },
    { slug: "money-settings", label: "Settings", icon: "Settings" },
  ],
  quiet: [
    { slug: "quiet-dashboard", label: "Dashboard", icon: "Brain" },
    { slug: "quiet-recommendations", label: "Recommendations", icon: "Lightbulb" },
    { slug: "quiet-external-new", label: "New Audit", icon: "ClipboardList" },
    { slug: "quiet-report", label: "Report", icon: "FileSearch" },
  ],
  vendor: [
    { slug: "vendor-dashboard", label: "Dashboard", icon: "LayoutDashboard" },
    { slug: "vendor-insights", label: "Demand Insights", icon: "TrendingUp" },
    { slug: "vendor-pricing", label: "Pricing", icon: "DollarSign" },
    { slug: "vendor-deals", label: "Deals", icon: "Tag" },
    { slug: "vendor-orders", label: "Orders", icon: "Inbox" },
    { slug: "vendor-messages", label: "Messages", icon: "MessageSquare" },
  ],
};
