import type { WorkflowStep } from "../types";

export const PROFILE_BUILDER_STEPS: WorkflowStep[] = [
  {
    id: "welcome",
    type: "info_card",
    question: "Let's build your profile",
    subtitle:
      "We'll ask you a few questions to personalise your Prep Mi experience. Takes about 2 minutes.",
    required: false,
  },
  {
    id: "name",
    type: "text_input",
    question: "What should we call you?",
    subtitle: "Your display name in Prep Mi",
    required: true,
    validate: (v) => (!v?.trim() ? "Please enter your name" : null),
  },
  {
    id: "theme",
    type: "grid_select",
    question: "Pick your vibe",
    subtitle: "Choose a colour theme for the app",
    options: [
      { label: "Pink Onion", value: "pink_onion", color: "#D94878" },
      { label: "Kitchen", value: "kitchen", color: "#C47A38" },
      { label: "Ocean Blue", value: "ocean", color: "#3B82C4" },
      { label: "Terminal", value: "terminal", color: "#4ADE80" },
      { label: "Lavender", value: "lavender", color: "#9B7AC4" },
      { label: "Rainbow", value: "rainbow", color: "#A855F7" },
    ],
    required: false,
  },
  {
    id: "household_size",
    type: "household_count",
    question: "How many mouths to feed?",
    subtitle: "Including yourself",
    min: 1,
    max: 8,
    required: true,
  },
  {
    id: "cuisines",
    type: "multi_select",
    question: "What cuisines do you love?",
    subtitle: "Pick as many as you like",
    options: [
      { label: "Italian", value: "italian" },
      { label: "Thai", value: "thai" },
      { label: "Mexican", value: "mexican" },
      { label: "Indian", value: "indian" },
      { label: "Japanese", value: "japanese" },
      { label: "Mediterranean", value: "mediterranean" },
      { label: "Chinese", value: "chinese" },
      { label: "French", value: "french" },
      { label: "Korean", value: "korean" },
      { label: "American", value: "american" },
      { label: "Middle Eastern", value: "middle_eastern" },
      { label: "Vietnamese", value: "vietnamese" },
      { label: "Greek", value: "greek" },
      { label: "Spanish", value: "spanish" },
      { label: "African", value: "african" },
      { label: "Caribbean", value: "caribbean" },
    ],
    required: false,
  },
  {
    id: "adventure_level",
    type: "scale",
    question: "How adventurous are you?",
    subtitle: "In the kitchen",
    options: [
      { label: "Play it safe", value: "1" },
      { label: "Curious", value: "2" },
      { label: "Adventurous", value: "3" },
      { label: "Surprise me", value: "4" },
    ],
    required: false,
  },
  {
    id: "spice_level",
    type: "scale",
    question: "Spice tolerance?",
    options: [
      { label: "Mild", value: "1" },
      { label: "Medium", value: "2" },
      { label: "Hot", value: "3" },
      { label: "Bring it on", value: "4" },
    ],
    required: false,
  },
  {
    id: "cooking_skill",
    type: "icon_cards",
    question: "Cooking confidence?",
    options: [
      {
        label: "Beginner",
        value: "beginner",
        icon: "Sprout",
        description: "Just getting started",
      },
      {
        label: "Intermediate",
        value: "intermediate",
        icon: "ChefHat",
        description: "Comfortable in the kitchen",
      },
      {
        label: "Advanced",
        value: "advanced",
        icon: "Flame",
        description: "I can improvise",
      },
    ],
    required: false,
  },
  {
    id: "weeknight_time",
    type: "slider",
    question: "Weeknight cooking time?",
    subtitle: "Maximum minutes you'll spend",
    min: 10,
    max: 90,
    step: 5,
    unit: "min",
    required: false,
  },
  {
    id: "weekend_time",
    type: "slider",
    question: "Weekend cooking time?",
    subtitle: "When you have more time",
    min: 15,
    max: 180,
    step: 15,
    unit: "min",
    required: false,
  },
  {
    id: "vessels",
    type: "multi_select",
    question: "What do you cook with?",
    subtitle: "Your kitchen essentials",
    options: [
      { label: "Pot", value: "pot" },
      { label: "Pan", value: "pan" },
      { label: "Oven Tray", value: "tray" },
      { label: "Wok", value: "wok" },
      { label: "Slow Cooker", value: "slow_cooker" },
      { label: "Air Fryer", value: "air_fryer" },
      { label: "Instant Pot", value: "instant_pot" },
      { label: "BBQ/Grill", value: "bbq" },
    ],
    required: false,
  },
  {
    id: "budget",
    type: "single_select",
    question: "Weekly food budget?",
    subtitle: "Per person, roughly",
    options: [
      { label: "Under $50", value: "tight" },
      { label: "$50 \u2013 $100", value: "moderate" },
      { label: "$100 \u2013 $150", value: "comfortable" },
      { label: "$150+", value: "flexible" },
    ],
    required: false,
  },
  {
    id: "dietary",
    type: "multi_select",
    question: "Any dietary needs?",
    subtitle: "Select all that apply",
    options: [
      { label: "None", value: "none" },
      { label: "Vegetarian", value: "vegetarian" },
      { label: "Vegan", value: "vegan" },
      { label: "Gluten Free", value: "gluten_free" },
      { label: "Dairy Free", value: "dairy_free" },
      { label: "Nut Free", value: "nut_free" },
      { label: "Halal", value: "halal" },
      { label: "Kosher", value: "kosher" },
      { label: "Low Carb", value: "low_carb" },
      { label: "Keto", value: "keto" },
    ],
    required: false,
  },
  {
    id: "shopping_style",
    type: "single_select",
    question: "How do you shop?",
    options: [
      { label: "Big weekly shop", value: "weekly_big" },
      { label: "Little and often", value: "little_often" },
      { label: "Online delivery", value: "online" },
      { label: "Mix of everything", value: "mixed" },
    ],
    required: false,
  },
  {
    id: "drink_preference",
    type: "single_select",
    question: "What about drinks?",
    subtitle: "To pair with your cooking",
    options: [
      { label: "Wine lover", value: "wine" },
      { label: "Cocktail fan", value: "cocktail" },
      { label: "Non-drinker", value: "non_drinker" },
      { label: "Bit of everything", value: "everything" },
    ],
    required: false,
  },
  {
    id: "personality",
    type: "personality_pick",
    question: "Which sounds most like you?",
    subtitle: "Your cooking personality",
    options: [
      {
        label: "Humpday Preper",
        value: "humpday_nosher",
        description: "Plans midweek, shops weekend, cooks with confidence",
      },
      {
        label: "Weekend Warrior",
        value: "weekend_warrior",
        description:
          "Saturday morning blitz \u2014 one trip, done by lunch",
      },
      {
        label: "Thrill Seeker",
        value: "thrill_seeker",
        description:
          "5pm sprint \u2014 nearest store, 15 minutes, sorted",
      },
      {
        label: "OCD Planner",
        value: "ocd_planner",
        description: "Full spreadsheet, batch prep, project-level cooks",
      },
    ],
    required: false,
  },
  {
    id: "complete",
    type: "info_card",
    question: "You're all set!",
    subtitle:
      "Your Prep Mi experience is now personalised. You can always update your profile from Settings.",
    required: false,
  },
];
