
-- Create help_articles table
CREATE TABLE public.help_articles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  module TEXT NOT NULL,
  page TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  subtitle TEXT DEFAULT '',
  icon TEXT DEFAULT 'HelpCircle',
  category TEXT NOT NULL DEFAULT 'feature',
  steps JSONB NOT NULL DEFAULT '[]'::jsonb,
  tags TEXT[] DEFAULT '{}',
  sort_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.help_articles ENABLE ROW LEVEL SECURITY;

-- Read access for all authenticated users
CREATE POLICY "Authenticated users can read published help articles"
ON public.help_articles FOR SELECT TO authenticated
USING (is_published = true);

-- Admin full access
CREATE POLICY "Admins can manage help articles"
ON public.help_articles FOR ALL TO authenticated
USING (public.is_admin(auth.uid()))
WITH CHECK (public.is_admin(auth.uid()));

-- Timestamp trigger
CREATE TRIGGER update_help_articles_updated_at
BEFORE UPDATE ON public.help_articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Seed help articles
INSERT INTO public.help_articles (module, page, title, subtitle, icon, category, steps, tags, sort_order) VALUES
-- ChefOS
('chefos', 'recipes', 'Creating Your First Recipe', 'Step-by-step guide to building a recipe with costing', 'ChefHat', 'getting-started', '[{"step_number":1,"title":"Navigate to Recipes","instruction":"Tap the Recipes icon in the sidebar or bottom navigation. This opens your recipe library.","tips":"Use the search bar to find existing recipes quickly."},{"step_number":2,"title":"Tap New Recipe","instruction":"Hit the + button or New Recipe card. Fill in the recipe name, category, and portion yield.","tips":"Choose a clear name — it will appear on prep lists and menus."},{"step_number":3,"title":"Add Ingredients","instruction":"Search your ingredient database and add each item with its quantity and unit. The cost calculates automatically.","tips":"If an ingredient is missing, you can create it inline."},{"step_number":4,"title":"Write the Method","instruction":"Add step-by-step cooking instructions. Each step can include a timer, temperature, and photo.","tips":"Use the voice dictation button to speak your method hands-free."},{"step_number":5,"title":"Review Costing","instruction":"Check the cost per portion, food cost %, and suggested sell price. Adjust portions or ingredients to hit your GP target.","tips":"Aim for 28-32% food cost for mains."}]', ARRAY['recipe','create','costing','new','beginner'], 1),

('chefos', 'ingredients', 'Managing Ingredients & Prices', 'Track costs, set par levels, and scan invoices', 'Carrot', 'feature', '[{"step_number":1,"title":"Add an Ingredient","instruction":"Go to Ingredients and tap +. Enter the name, unit, category, supplier, and cost per unit.","tips":"Use consistent units (kg, L, each) across your kitchen."},{"step_number":2,"title":"Set Par Levels","instruction":"Set a minimum stock level for each ingredient. You''ll get alerts when stock drops below par.","tips":"Base par levels on your busiest day''s usage."},{"step_number":3,"title":"Scan an Invoice","instruction":"Use the invoice scanner to photograph a supplier invoice. AI extracts prices and updates your ingredient costs automatically.","tips":"Take photos in good lighting for best OCR results."},{"step_number":4,"title":"Track Price History","instruction":"View the price trend chart for any ingredient. See how costs have changed over time and spot spikes.","tips":"Set price alerts to catch unexpected increases."}]', ARRAY['ingredients','prices','par','invoice','stock'], 2),

('chefos', 'prep', 'Daily Prep Lists', 'Set up and manage your prep workflow', 'ClipboardList', 'workflow', '[{"step_number":1,"title":"Create a Prep List","instruction":"Navigate to Prep Lists and create a new list for the day. Choose your template or start fresh.","tips":"Create templates for each day of the week."},{"step_number":2,"title":"Assign Tasks","instruction":"Add prep tasks with quantities, assign to team members, and set priority levels.","tips":"Front-load high-priority items for the morning crew."},{"step_number":3,"title":"Track Completion","instruction":"Team members tick off tasks as they complete them. Progress updates in real-time.","tips":"Use the timer integration for time-critical prep tasks."}]', ARRAY['prep','daily','tasks','assign','kitchen'], 3),

('chefos', 'inventory', 'Stock Counts & Inventory', 'Run efficient stock counts and track usage', 'Package', 'workflow', '[{"step_number":1,"title":"Start a Stock Count","instruction":"Go to Inventory and tap Start Count. Select the areas to count (walk-in, dry store, freezer).","tips":"Count at the same time each day for consistency."},{"step_number":2,"title":"Count Items","instruction":"Enter quantities for each item. The app shows expected vs actual with variance highlighting.","tips":"Use the barcode scanner for speed."},{"step_number":3,"title":"Review Variances","instruction":"Check items with significant variances. Investigate waste, theft, or recording errors.","tips":"Variances over 5% should be investigated immediately."}]', ARRAY['inventory','stock','count','variance','waste'], 4),

('chefos', 'menu-engineering', 'Menu Engineering Analysis', 'Use Stars, Dogs, Puzzles & Plowhorses to optimise your menu', 'TrendingUp', 'feature', '[{"step_number":1,"title":"Understanding the Matrix","instruction":"Menu Engineering plots every dish on a 2x2 grid: Popularity (volume sold) vs Profitability (contribution margin).","tips":"Stars = high profit + high popularity. Keep and promote these."},{"step_number":2,"title":"Identify Your Dogs","instruction":"Dogs are low profit AND low popularity. Consider removing or reworking these dishes.","tips":"Sometimes a recipe tweak can turn a Dog into a Puzzle."},{"step_number":3,"title":"Optimise Pricing","instruction":"Use the suggested price adjustments. The system calculates ideal prices based on food cost targets and competitor benchmarks.","tips":"Small price changes (5-10%) are usually unnoticed by customers."}]', ARRAY['menu','engineering','stars','dogs','profitability','margin'], 5),

('chefos', 'food-safety', 'Food Safety & HACCP', 'Temperature logs, cleaning verification, and CCP management', 'ShieldCheck', 'feature', '[{"step_number":1,"title":"Log Temperatures","instruction":"Tap the temperature logger and select the equipment (fridge, freezer, hot hold). Enter the reading.","tips":"Log at opening, mid-service, and closing."},{"step_number":2,"title":"Record CCPs","instruction":"For each Critical Control Point, record the actual value against the target. Failed CCPs trigger alerts.","tips":"Take corrective action immediately on any CCP failure."},{"step_number":3,"title":"Cleaning Verification","instruction":"Complete cleaning checklists with photo evidence. The system tracks completion rates by area.","tips":"Use the reference photos to show the expected standard."}]', ARRAY['food-safety','haccp','temperature','cleaning','ccp'], 6),

('chefos', 'kitchen-sections', 'Kitchen Sections & Stations', 'Organise your kitchen by section and assign staff', 'Layout', 'feature', '[{"step_number":1,"title":"Create Sections","instruction":"Go to Kitchen Sections and define your stations: Grill, Sauté, Pastry, Cold, etc.","tips":"Match sections to your physical kitchen layout."},{"step_number":2,"title":"Assign Staff","instruction":"Assign chefs to sections with roles (Leader, Cook). Leaders manage their section''s prep and quality.","tips":"Rotate assignments to cross-train your team."},{"step_number":3,"title":"Link Recipes","instruction":"Assign recipes to sections so prep lists and KDS tickets route correctly.","tips":"A recipe can belong to multiple sections if needed."}]', ARRAY['sections','stations','kitchen','assign','staff'], 7),

('chefos', 'invoices', 'Invoice Scanning & Price Updates', 'Use AI to extract data from supplier invoices', 'FileText', 'feature', '[{"step_number":1,"title":"Upload an Invoice","instruction":"Go to Invoices and tap Scan. Take a photo or upload a PDF of your supplier invoice.","tips":"Ensure the invoice is well-lit and flat for best results."},{"step_number":2,"title":"Review Extraction","instruction":"AI extracts line items, quantities, and prices. Review and confirm each item.","tips":"The AI learns from corrections — accuracy improves over time."},{"step_number":3,"title":"Apply Price Updates","instruction":"Confirm which ingredient prices should be updated. Changes flow through to all recipe costings.","tips":"Check the price change summary before applying."}]', ARRAY['invoices','scan','ai','prices','supplier'], 8),

('chefos', 'production', 'Production & Yield Testing', 'Batch scaling, waste tracking, and yield calculations', 'Factory', 'feature', '[{"step_number":1,"title":"Run a Yield Test","instruction":"Select a recipe and record raw weight vs cooked weight. The system calculates your yield percentage.","tips":"Run yield tests 3 times for accuracy."},{"step_number":2,"title":"Scale a Batch","instruction":"Enter the number of portions needed. Ingredients scale automatically with waste factors applied.","tips":"Check the scaled quantities make sense — round to practical amounts."}]', ARRAY['production','yield','batch','scale','waste'], 9),

('chefos', 'cheatsheets', 'Cheatsheets & Timers', 'Quick reference guides and smart timer setup', 'BookOpen', 'feature', '[{"step_number":1,"title":"Browse Cheatsheets","instruction":"Access cooking reference cards: temperature guides, conversion charts, sauce mothers, knife cuts.","tips":"Pin your most-used cheatsheets for quick access."},{"step_number":2,"title":"Set Up Smart Timers","instruction":"Create timers for any cooking process. Chain timers together for multi-step recipes.","tips":"Critical timers alert the entire KDS screen when they expire."}]', ARRAY['cheatsheets','timers','reference','guide','cooking'], 10),

-- BevOS
('bevos', 'cellar', 'Wine Cellar Management', 'Track inventory, vintages, and Coravin pours', 'Wine', 'getting-started', '[{"step_number":1,"title":"Add Wine to Cellar","instruction":"Go to Cellar and add a new wine. Enter producer, varietal, vintage, region, and bin number.","tips":"Use the barcode scanner for quick entry."},{"step_number":2,"title":"Track Open Bottles","instruction":"When opening a bottle, tap Open. Track remaining ml and expiry for by-the-glass service.","tips":"Coravin-preserved wines last weeks longer."},{"step_number":3,"title":"Run Stocktake","instruction":"Count bottles by bin location. The system flags variances against expected stock.","tips":"Count by section: whites, reds, sparkling, fortified."}]', ARRAY['wine','cellar','inventory','coravin','vintage'], 11),

('bevos', 'cocktails', 'Cocktail Spec Builder', 'Create recipes, calculate costings, and batch prep', 'GlassWater', 'feature', '[{"step_number":1,"title":"Create a Spec","instruction":"Name your cocktail, set the category, and add ingredients with exact ml measurements.","tips":"Include garnish and ice type for complete specs."},{"step_number":2,"title":"Check Costing","instruction":"Cost per drink calculates automatically. Adjust sell price to hit your target GP%.","tips":"Aim for 80%+ GP on cocktails."},{"step_number":3,"title":"Batch Recipe","instruction":"Toggle batch mode. Enter batch volume and the recipe scales. Print batch labels.","tips":"Pre-batch your top 5 sellers for speed."}]', ARRAY['cocktails','spec','recipe','batch','costing'], 12),

('bevos', 'draught', 'Draught & Keg Management', 'Tap tracking, line cleaning, and pour yields', 'Beer', 'feature', '[{"step_number":1,"title":"Set Up Taps","instruction":"Assign products to tap numbers. Enter keg size and expected pours per keg.","tips":"Label tap numbers to match your physical taps."},{"step_number":2,"title":"Track Keg Yields","instruction":"When a keg kicks, record actual pours vs theoretical. Calculate yield percentage.","tips":"Yields below 85% indicate pouring issues."},{"step_number":3,"title":"Log Line Cleaning","instruction":"Record each line clean with chemical used and next due date. Get reminders when overdue.","tips":"Clean every 2 weeks minimum. Weekly is best practice."}]', ARRAY['draught','keg','taps','cleaning','yield'], 13),

('bevos', 'coffee', 'Coffee & Espresso Program', 'Dialling in, dose tracking, and brew recipes', 'Coffee', 'feature', '[{"step_number":1,"title":"Dial In Espresso","instruction":"Record dose (g), yield (ml), time (s), and TDS for each dial-in. Track grinder settings.","tips":"Target 1:2 ratio (e.g., 20g in → 40ml out) in 25-30 seconds."},{"step_number":2,"title":"Set Brew Recipes","instruction":"Create recipes for each brew method: pour-over, cold brew, batch brew. Include grind, ratio, and temperature.","tips":"Different origins may need different brew parameters."}]', ARRAY['coffee','espresso','dial','brew','grind'], 14),

('bevos', 'stocktake', 'Beverage Stocktake', 'Count sheets, variance analysis, and cost tracking', 'ClipboardCheck', 'workflow', '[{"step_number":1,"title":"Start a Count","instruction":"Select Full Count or Spot Check. Walk through each storage area counting bottles, kegs, and cases.","tips":"Weigh open bottles for accurate partial counts."},{"step_number":2,"title":"Review Variances","instruction":"The system calculates expected vs actual based on POS sales. Investigate large variances.","tips":"Variance over $50 per product warrants investigation."}]', ARRAY['stocktake','count','variance','beverage','inventory'], 15),

('bevos', 'flash-cards', 'Staff Training Flash Cards', 'Create and study product knowledge cards', 'GraduationCap', 'feature', '[{"step_number":1,"title":"Create Flash Cards","instruction":"Add cards with product info: tasting notes, food pairings, production method, region.","tips":"Include images for visual learners."},{"step_number":2,"title":"Quiz Mode","instruction":"Staff can test themselves with randomized quiz questions. Track scores and completion.","tips":"Run weekly quizzes to keep knowledge fresh."}]', ARRAY['flash-cards','training','quiz','knowledge','staff'], 16),

('bevos', 'bar-prep', 'Bar Prep & Infusions', 'Garnish lists, batch prep, and infusion tracking', 'FlaskConical', 'workflow', '[{"step_number":1,"title":"Create Bar Prep List","instruction":"Set up daily prep tasks: cut garnishes, juice citrus, batch cocktails, check infusions.","tips":"Use templates for different days of the week."},{"step_number":2,"title":"Track Infusions","instruction":"Start an infusion with base spirit, ingredient, and target completion date. Get alerts when ready.","tips":"Taste daily and pull early if flavour is right."}]', ARRAY['bar-prep','garnish','infusion','batch','prep'], 17),

('bevos', 'wine', 'Wine Intelligence & AI Sommelier', 'AI-powered pairing suggestions and wine education', 'Sparkles', 'feature', '[{"step_number":1,"title":"Get Pairing Suggestions","instruction":"Enter a dish or ingredient and the AI suggests wines from your cellar that pair well.","tips":"The AI considers your current inventory and price range."},{"step_number":2,"title":"Wine Education","instruction":"Access tasting wheels, region maps, and grape variety guides. Use for staff training.","tips":"Start with the 6 noble grapes for staff foundations."}]', ARRAY['wine','ai','pairing','sommelier','education'], 18),

-- RestOS
('restos', 'pos', 'Taking Orders on POS', 'Complete order flow from table to kitchen', 'Monitor', 'getting-started', '[{"step_number":1,"title":"Select a Table","instruction":"Tap the table number on the floor plan or enter it manually. This opens the order screen.","tips":"Use the quick-select numpad for speed."},{"step_number":2,"title":"Add Items","instruction":"Browse categories or search for menu items. Tap to add, long-press for modifiers.","tips":"Star your top 10 items for the quick-access bar."},{"step_number":3,"title":"Fire to Kitchen","instruction":"Review the order and tap Send. Items route to the correct KDS station automatically.","tips":"Use Course buttons to control firing sequence."},{"step_number":4,"title":"Process Payment","instruction":"Tap Pay, select payment method (cash, card, split). Print or email receipt.","tips":"Split bills by item or by equal share."}]', ARRAY['pos','order','payment','table','kitchen'], 19),

('restos', 'kds', 'Kitchen Display System', 'Manage tickets, routing, and timer integration', 'LayoutGrid', 'feature', '[{"step_number":1,"title":"Understand the Screen","instruction":"KDS shows active tickets ordered by time. Each station sees only its items. Colour coding shows urgency.","tips":"Green = on time, Amber = warning, Red = overdue."},{"step_number":2,"title":"Bump Tickets","instruction":"When an order is ready, tap to bump it. It moves to the pass screen for expo.","tips":"Double-tap to partially bump (some items ready, others not)."},{"step_number":3,"title":"Use Timers","instruction":"Smart timers integrate with KDS. When a timer fires, the associated ticket flashes.","tips":"Set ticket target times per category (starters 8min, mains 15min)."}]', ARRAY['kds','kitchen','display','tickets','timer'], 20),

('restos', 'tabs', 'Bar Tabs & Function Billing', 'Manage open tabs and event billing', 'CreditCard', 'feature', '[{"step_number":1,"title":"Open a Tab","instruction":"Tap New Tab, enter the guest name and optional card hold. Add items as they order.","tips":"Set tab limits to manage risk."},{"step_number":2,"title":"Close a Tab","instruction":"Review all items, apply any discounts, and process payment. Tab history is saved to the guest profile.","tips":"Print an itemized receipt for transparency."}]', ARRAY['tabs','bar','billing','function','payment'], 21),

('restos', 'analytics', 'Sales Analytics & Reports', 'Hourly breakdowns, category analysis, and trends', 'BarChart3', 'feature', '[{"step_number":1,"title":"View Dashboard","instruction":"The analytics dashboard shows today''s revenue, covers, avg ticket, and hourly breakdown.","tips":"Compare to same day last week for context."},{"step_number":2,"title":"Run Reports","instruction":"Generate reports by date range: category sales, staff performance, discount analysis.","tips":"Export to CSV for your accountant."}]', ARRAY['analytics','sales','reports','revenue','trends'], 22),

('restos', 'admin/menu', 'Menu Administration', 'Item setup, modifiers, and pricing management', 'Settings', 'workflow', '[{"step_number":1,"title":"Add Menu Items","instruction":"Create items with name, category, price, and kitchen station routing.","tips":"Use consistent naming: Chicken Parmigiana not Parma."},{"step_number":2,"title":"Set Up Modifiers","instruction":"Create modifier groups (Size, Temperature, Extras) and assign to items.","tips":"Set default modifiers to speed up ordering."},{"step_number":3,"title":"Manage Pricing","instruction":"Update prices individually or in bulk. Price changes take effect immediately.","tips":"Use the margin calculator to ensure profitability."}]', ARRAY['menu','admin','items','modifiers','pricing'], 23),

-- LabourOS
('labouros', 'roster', 'Building Rosters', 'Create shifts, use templates, and manage availability', 'Calendar', 'getting-started', '[{"step_number":1,"title":"Create a Roster","instruction":"Go to Roster and select the week. Add shifts by dragging or tapping time slots.","tips":"Start with a template and adjust for the week."},{"step_number":2,"title":"Assign Staff","instruction":"Drag staff into shifts or use auto-fill based on availability and skills.","tips":"Check labour cost % as you build — aim for 28-32%."},{"step_number":3,"title":"Publish","instruction":"Review the roster and publish. Staff get notified of their shifts via the app.","tips":"Publish at least 7 days ahead to comply with most awards."}]', ARRAY['roster','shifts','schedule','staff','template'], 24),

('labouros', 'timesheets', 'Timesheet Approval', 'Review, adjust, and approve time records', 'Clock', 'workflow', '[{"step_number":1,"title":"Review Timesheets","instruction":"Go to Timesheets to see clock-in/out records for the period. Flagged entries need attention.","tips":"Check for missed clock-outs and overtime."},{"step_number":2,"title":"Approve or Adjust","instruction":"Approve correct entries, adjust incorrect ones with a note. Bulk-approve clean records.","tips":"Adjust before approving — approved records go to payroll."}]', ARRAY['timesheets','approval','clock','hours','adjust'], 25),

('labouros', 'payroll', 'Running Payroll', 'Pay run creation and award interpretation', 'DollarSign', 'workflow', '[{"step_number":1,"title":"Create Pay Run","instruction":"Go to Payroll and start a new pay run. Select the period and review the calculated amounts.","tips":"Check that overtime and penalty rates are applied correctly."},{"step_number":2,"title":"Review & Process","instruction":"Review each employee''s pay breakdown: base, overtime, penalties, allowances. Export to your payroll system.","tips":"Keep payroll records for 7 years as required by law."}]', ARRAY['payroll','pay-run','wages','awards','overtime'], 26),

('labouros', 'compliance', 'Labour Compliance', 'Break tracking, certificates, and award compliance', 'ShieldAlert', 'feature', '[{"step_number":1,"title":"Break Tracking","instruction":"The system monitors break compliance against award requirements. Alerts fire for missed breaks.","tips":"Ensure breaks are taken within the required window."},{"step_number":2,"title":"Certificate Management","instruction":"Track RSA, food handler, first aid, and other certificates. Get expiry alerts.","tips":"Set 30-day advance warnings for renewals."}]', ARRAY['compliance','breaks','certificates','awards','rsa'], 27),

-- MoneyOS
('moneyos', 'reactor', 'Reading the Reactor Dashboard', 'Understanding alerts, pulse metrics, and ecosystem health', 'Atom', 'getting-started', '[{"step_number":1,"title":"The Pulse Strip","instruction":"The top row shows your key metrics: Revenue, Food%, Labour%, Net Profit%. Green = target met, Red = needs attention.","tips":"Tap any metric to drill into the detail view."},{"step_number":2,"title":"Ecosystem Status","instruction":"The status grid shows all connected modules. Green dots = live data, amber = stale, red = disconnected.","tips":"Stale data means decisions are based on old information."},{"step_number":3,"title":"Alert Feed","instruction":"Active alerts are prioritised by severity. High = act now, Medium = investigate today, Low = track.","tips":"Swipe right on an alert to mark as actioned."},{"step_number":4,"title":"Cross-Product Correlations","instruction":"Charts show relationships between metrics: Revenue vs Labour, Weather vs Covers, etc.","tips":"Look for patterns that predict problems before they happen."}]', ARRAY['reactor','dashboard','alerts','pulse','ecosystem'], 28),

('moneyos', 'pnl', 'Understanding the P&L', 'Waterfall charts, period comparisons, and true cost analysis', 'BarChart3', 'feature', '[{"step_number":1,"title":"The Waterfall","instruction":"Revenue flows down through costs to net profit. Each bar shows a cost category with its percentage.","tips":"Compare MTD vs last month to spot trends early."},{"step_number":2,"title":"Period Comparison","instruction":"Toggle to compare any two periods side by side. See where costs are creeping up.","tips":"Week-over-week is more actionable than month-over-month."}]', ARRAY['pnl','profit','loss','waterfall','comparison'], 29),

('moneyos', 'simulator', 'What-If Simulator', 'Run scenarios and Monte Carlo simulations', 'FlaskConical', 'feature', '[{"step_number":1,"title":"Create a Scenario","instruction":"Set up a what-if: What happens if food cost rises 3%? If we add 10 covers per night? If we cut one staff member?","tips":"Change one variable at a time for clear insights."},{"step_number":2,"title":"Run Monte Carlo","instruction":"The simulator runs 1000+ scenarios with random variations. See the probability distribution of outcomes.","tips":"Focus on the 10th percentile — that''s your downside risk."}]', ARRAY['simulator','what-if','monte-carlo','scenario','forecast'], 30),

('moneyos', 'forensic', 'Forensic Audit', 'Upload data for deep-dive True P&L analysis', 'FileSearch', 'feature', '[{"step_number":1,"title":"Upload Documents","instruction":"Upload your BAS, bank statements, POS reports, and supplier invoices for the period.","tips":"More data = more accurate True P&L."},{"step_number":2,"title":"True P&L vs Claimed","instruction":"See the difference between what your books say and what actually happened. Identify hidden costs.","tips":"Focus on the gap — that''s where money is leaking."}]', ARRAY['forensic','audit','true-pnl','upload','analysis'], 31),

('moneyos', 'audit', 'Quiet Audit Score', 'Understanding your 7-module health score', 'ShieldCheck', 'feature', '[{"step_number":1,"title":"Overall Score","instruction":"Your Quiet Audit score is a weighted average across 7 modules: Labour, Overhead, Food, Service, Beverage, Marketing, Compliance.","tips":"A score above 80 is Good, 60-80 is Fair, below 60 needs urgent attention."},{"step_number":2,"title":"Module Breakdown","instruction":"Tap each module to see sub-scores and specific recommendations.","tips":"Focus on the lowest-scoring module first for maximum impact."},{"step_number":3,"title":"Trend Direction","instruction":"The arrow shows whether your score is improving or declining. Track weekly.","tips":"Consistent improvement is more important than absolute score."}]', ARRAY['audit','score','quiet','modules','health'], 32),

-- ReservationOS
('reservationos', 'diary', 'Reservation Diary', 'Booking flow, table assignment, and walk-ins', 'CalendarDays', 'getting-started', '[{"step_number":1,"title":"View the Diary","instruction":"The diary shows all bookings for the day in a timeline view. Each booking shows name, covers, and assigned table.","tips":"Use the week view to spot busy periods ahead."},{"step_number":2,"title":"Take a Booking","instruction":"Tap a time slot or use New Booking. Enter guest name, covers, date, time, and any notes.","tips":"Check availability before confirming — the system shows conflicts."},{"step_number":3,"title":"Manage Walk-ins","instruction":"Add walk-ins to the diary with estimated wait time. They appear in the waitlist.","tips":"Track walk-in volume to optimise staffing."}]', ARRAY['diary','booking','reservation','walk-in','table'], 33),

('reservationos', 'floor', 'Floor Plan Management', 'Table layout, sections, and capacity management', 'Map', 'feature', '[{"step_number":1,"title":"Set Up Floor Plan","instruction":"Drag and drop tables onto the floor plan. Set covers capacity for each table.","tips":"Match your digital layout to your physical floor exactly."},{"step_number":2,"title":"Create Sections","instruction":"Group tables into sections and assign servers. This helps with workload distribution.","tips":"Balance covers per section, not just table count."}]', ARRAY['floor','plan','tables','sections','layout'], 34),

('reservationos', 'guests', 'Guest CRM & Profiles', 'Track preferences, VIPs, and visit history', 'Users', 'feature', '[{"step_number":1,"title":"View Guest Profiles","instruction":"Each guest has a profile with visit history, spend data, preferences, and dietary requirements.","tips":"VIP guests get a gold star badge on their bookings."},{"step_number":2,"title":"Add Notes","instruction":"Add notes after each visit: what they enjoyed, special occasions, feedback.","tips":"Pre-shift briefing should include tonight''s VIP notes."}]', ARRAY['guests','crm','vip','preferences','profile'], 35),

('reservationos', 'functions', 'Event & Function Booking', 'Proposals, BEOs, and event management', 'PartyPopper', 'feature', '[{"step_number":1,"title":"Create an Event","instruction":"Go to Functions and create a new event. Set date, time, space, guest count, and event type.","tips":"Block the space in the diary when confirmed."},{"step_number":2,"title":"Build a Proposal","instruction":"Select menu packages, beverages, AV requirements, and calculate the quote. Send directly to the client.","tips":"Include terms and conditions in every proposal."},{"step_number":3,"title":"Generate BEO","instruction":"Once confirmed, generate a Banquet Event Order with all details for kitchen, bar, and service teams.","tips":"Print and distribute BEOs 48 hours before the event."}]', ARRAY['functions','events','proposal','beo','booking'], 36),

-- OverheadOS
('overheados', 'dashboard', 'Overhead Cost Tracking', 'Categorise, track, and benchmark your overheads', 'Building2', 'getting-started', '[{"step_number":1,"title":"Add Cost Categories","instruction":"Set up your overhead categories: rent, utilities, insurance, repairs, marketing, admin, etc.","tips":"Match categories to your chart of accounts."},{"step_number":2,"title":"Enter Costs","instruction":"Add each cost with amount, frequency (monthly/quarterly/annual), and category.","tips":"Set up recurring costs to auto-populate each period."},{"step_number":3,"title":"Track Against Benchmarks","instruction":"Compare your overhead % to industry benchmarks. See where you''re overspending.","tips":"Total overheads should be 15-25% of revenue."}]', ARRAY['overhead','costs','tracking','benchmark','expenses'], 37),

('overheados', 'breakeven', 'Break-Even Analysis', 'Calculate your daily break-even revenue target', 'Target', 'feature', '[{"step_number":1,"title":"Set Fixed Costs","instruction":"Enter all fixed costs: rent, insurance, loan repayments, salaried staff.","tips":"Include ALL costs that don''t change with volume."},{"step_number":2,"title":"Calculate Break-Even","instruction":"The system calculates your daily break-even in dollars and covers based on your average ticket.","tips":"Know this number by heart — it''s the most important number in your business."}]', ARRAY['breakeven','fixed-costs','target','revenue','daily'], 38),

-- GrowthOS
('growthos', 'campaigns', 'Marketing Campaigns', 'Create, schedule, and track marketing campaigns', 'Megaphone', 'getting-started', '[{"step_number":1,"title":"Create a Campaign","instruction":"Go to Campaigns and hit New. Set the objective, target audience, channels, and budget.","tips":"Start with one channel and expand based on results."},{"step_number":2,"title":"Track Performance","instruction":"Monitor reach, engagement, conversions, and ROI in real-time.","tips":"A/B test your messaging for best results."}]', ARRAY['campaigns','marketing','growth','social','advertising'], 39),

('growthos', 'segments', 'Customer Segmentation', 'Build targeted audiences for personalised marketing', 'Target', 'feature', '[{"step_number":1,"title":"Create Segments","instruction":"Define customer segments based on visit frequency, spend, preferences, and demographics.","tips":"Start with RFM: Recency, Frequency, Monetary value."},{"step_number":2,"title":"Target Campaigns","instruction":"Send targeted offers to specific segments. Track response rates by segment.","tips":"Personalised messages get 3x higher response rates."}]', ARRAY['segments','audience','targeting','crm','personalisation'], 40),

-- ClockOS
('clockos', 'clock', 'Clocking In & Out', 'Time tracking for all staff', 'Clock', 'getting-started', '[{"step_number":1,"title":"Clock In","instruction":"Enter your PIN on the clock screen. Your shift starts recording. Take a photo for verification.","tips":"Clock in at your scheduled start time — not before."},{"step_number":2,"title":"Clock Out","instruction":"Enter your PIN again to clock out. Your hours are automatically added to timesheets.","tips":"Don''t forget to clock out — missed clock-outs flag for manager review."}]', ARRAY['clock','time','pin','shift','attendance'], 41),

('clockos', 'dashboard', 'Clock Dashboard', 'Who''s working now and shift overview', 'LayoutDashboard', 'feature', '[{"step_number":1,"title":"Live View","instruction":"See who is currently clocked in, their shift duration, and scheduled end time.","tips":"Check for overtime approaching in the amber zone."},{"step_number":2,"title":"Manage Devices","instruction":"Set up clock-in devices (tablets, phones) with geo-fencing to prevent remote clock-ins.","tips":"Set the geo-fence radius to 100m around your venue."}]', ARRAY['dashboard','live','overview','devices','geofence'], 42),

-- SupplyOS
('supplyos', 'orders', 'Placing Supply Orders', 'Order from suppliers with smart par-level suggestions', 'ShoppingCart', 'getting-started', '[{"step_number":1,"title":"Review Suggestions","instruction":"The system suggests order quantities based on par levels, current stock, and upcoming bookings.","tips":"Review on the same day each week for consistency."},{"step_number":2,"title":"Place Orders","instruction":"Select items, adjust quantities, and send orders directly to suppliers.","tips":"Consolidate orders to reduce delivery fees."}]', ARRAY['orders','supply','purchase','supplier','par'], 43),

('supplyos', 'price-watch', 'Price Watch & Comparison', 'Track supplier pricing and find the best deals', 'Eye', 'feature', '[{"step_number":1,"title":"Compare Prices","instruction":"See the same product across multiple suppliers. Sort by price, delivery time, or minimum order.","tips":"Price isn''t everything — consider quality and reliability."},{"step_number":2,"title":"Set Alerts","instruction":"Get notified when prices change significantly or when better deals become available.","tips":"Check vendor deals weekly in the marketplace."}]', ARRAY['price','comparison','supplier','deals','watch'], 44);
